name: Host PDF

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo code
      uses: actions/checkout@v3
    - name: Convert yaml to PDF via TEX template
      uses: ./.github/actions/pandoc 
      with:
        args: >-
          resume.yaml
          --template ./resume.tex
          -o vinay_mehta_resume.pdf
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        file_pattern: ./*.pdf
        commit_message: Generate PDF
